### ISSUE TITLE
Consider using atom-isort instead of atom-python-isort

### ISSUE THREAD

**Issue by lexicalunit** [serafeimgr/pythonic-atom#1]
Sadly, [`atom-python-isort`](https://github.com/bh/atom-python-isort) hasn't been maintained for over three years now. There's more than a dozen unaddressed issues and a few open pull requests that are going nowhere. I've been maintaining [`atom-isort`](https://github.com/lexicalunit/atom-isort) for the last year. I've fixed the long standing bugs and made a number of enhancements such as:

- Integration with Atom's linter
- Error handling and reporting via Atom's notification manager
- A small but growing spec test suite to avoid future regressions

Plus I'm still actively developing and improving this package. I have a plans to refactor some parts of the codebase for performance and usability. I also want to migrate the codebase to ES6 and improve the README documentation.

**Comment by serafeimgr** [comment]
Hello,

Your request makes sense, i was not aware of atom-isort.
I will replace atom-python-isort with atom-isort in the next release of pythonic-atom.

If there is anything else you want to tackle, please do not hesitate to open another issue.

Also if you are aware of any other python featured package, that may be useful to include to pythonic-atom, please feel free to contribute.

**Comment by serafeimgr** [comment]
Hello again,
I have pushed the changes.
Let me know if you need anything else.
