### ISSUE TITLE
Hydrogen

### ISSUE THREAD

**Issue by brennv** [serafeimgr/pythonic-atom#2]
Cool project, this definitely makes setup easier. The only other package I might add is [Hydrogen](https://github.com/nteract/hydrogen).

**Comment by serafeimgr** [comment]
Hello, 
Just pushed the changes to support Hydrogen.
I also added an extra setting into hydrogen upon installation because Hydrogen does not support MagicPython out of the box and requires a language mapping.

Thanks for the proposal.
Serafeim
